//WHAT WE WILL DO

//string eg
let a = "jaat"
console.log(a)

//@ESCAPE CHARACHTER
//@FINDINAG A STRING IN A STRING
//@SEARCHING FOR A STRING IN A STRING
//@EXTRACTING STRING PARTS
//@REPLACING STRING CONTENT
//@EXTRACTIONG STRING CHARACHTERS
//@OTHER USE FULL METHODS 